"""add created_at to sends

Revision ID: b40588ef58fd
Revises: ebebcaa0d3e7
Create Date: 2026-05-10 20:03:00.966570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40588ef58fd'
down_revision: Union[str, Sequence[str], None] = 'ebebcaa0d3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sends', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sends', 'created_at')
    # ### end Alembic commands ###
